#!/usr/bin/env sh
# fetch Clastran~Al~Us (US) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://www.clastran.com/_files/archives/866304_1257fc996ab741c69f3afd6a25304e90.zip?dn=2025.02.07%20Columbiana%20Trolley%20GTFS%20Feed%20(latest%20version).zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
