#!/usr/bin/env sh
# fetch Kumanogobobus~Kumanogobobus~Kumano (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/kumanogobobus/feeds/kumanogobobus_kumano/files/feed.zip?uid=dea2c3f7-2070-4e13-b70d-3b9f24481d98"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
