#!/usr/bin/env sh
# fetch Yangon Bus Service (YBS) — Yangon Region Public Transport Committee (YRTC, formerly YRTA); 8 private operators incl. Omni Focus, YBPC, KBG, LuDu, YUPT, BDL, GYCT, TRAN (MM) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://raw.githubusercontent.com/jqueguiner/gtfs/main/synthesized/MM/yangon/yangon-bus-service-ybs-yangon-region-public-tran/gtfs/"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
