#!/usr/bin/env sh
# fetch 長岡市~小国地域生活交通~法末線 (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://www.city.nagaoka.niigata.jp/shisei/cate10/gis/file/28-11.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
