#!/usr/bin/env sh
# fetch Nangokucity~Gtfs~Nankokucity~Airportshare (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/nangokucity/feeds/GTFS-Nankokucity_AirportShare/files/feed.zip?uid=fb21978e-d8aa-4f29-9d88-6836f985aa5c"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
