#!/usr/bin/env sh
# fetch Guangzhou Public Transport Group bus companies (一汽/二汽/三汽/电车巴士 - Yiqi, 2nd, 3rd, Trolleybus) (CN) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://raw.githubusercontent.com/jqueguiner/gtfs/main/synthesized/CN/guangzhou/guangzhou-public-transport-group-bus-companies-y/gtfs/"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
