#!/usr/bin/env sh
# fetch Trentino Trasporti / STA (tndigit, app 'Muoversi in Trentino') (IT) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://app-tpl.tndigit.it/gtlservice/trips_new?routeId={routeId}&type=U"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
