#!/usr/bin/env sh
# fetch ATU - Autoridad de Transporte Urbano para Lima y Callao (Metropolitano BRT, Metro Line 1 & 2, corredores complementarios Rojo/Azul/Morado) (PE) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://github.com/trufi-association/gtfs-lima"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
