#!/usr/bin/env sh
# fetch Chatham Kent Transit (Ride CK) (CA) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://ck.usetransit.com/api/1/public/gtfs/5/gtfs.zip?token=eddbcb1b954b64461%21%219687922751%24-%24%409cc77671a2df2f%5E"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
