#!/usr/bin/env sh
# fetch Seoul TOPIS (Seoul Metropolitan Govt) — real-time bus GPS position by route (KR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="http://ws.bus.go.kr/api/rest/buspos/getBusPosByRtid?busRouteId={id}&serviceKey={KEY}"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
