#!/usr/bin/env sh
# fetch VRR (Verkehrsverbund Rhein-Ruhr) — incl. Rheinbahn Dusseldorf, Bogestra Bochum, DVG Duisburg, moBiel Bielefeld (DE) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://www.opendata-oepnv.de/dataset/496eea5d-d6ef-4dc2-aeb0-d15c4fbf3178/resource/46ea57c2-506c-4b2a-bc40-b680b1979f93/download/20250829_gtfs_vrr_od.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
