#!/usr/bin/env sh
# fetch Železnice Slovenskej republiky (ŽSR) / ZSSK (SK) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://data.slovensko.sk/download?id=c5a63281-3c44-4dba-82c9-7b7ad603db5d"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
