#!/usr/bin/env sh
# fetch Saint Maryʼs Transit System (US) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://stmgis.stmarysmd.com/Downloads/GTFS/StMarys_GTFS_5_31_22.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
