#!/usr/bin/env sh
# fetch Kalkaska~Public~Transit~Authority~Mi~Us (US) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://img1.wsimg.com/blobby/go/c8af6a6d-67d8-4429-b7ec-3fefc453da10/downloads/6c8055e7-dacf-4207-bf23-0d2472d8d10b/KPTA_GTFS.zip?ver=1775756557796"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
