#!/usr/bin/env sh
# fetch Filibus - Chartres Métropole Transports (FR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://static.data.gouv.fr/resources/reseau-filibus/20260922-102023/gtfs-filibus-20260919-20270702.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
