#!/usr/bin/env sh
# fetch Oxford~University~Transit~Ms~Us (US) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://www.outransit.com/_files/archives/00f7ca_da222b72511042ee91defff282d6a35a.zip?dn=All_Fixed_Routes-2026-05-20-18-08-04-gtfs.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
