#!/usr/bin/env sh
# fetch GCR combined: Cairo Transport Authority (CTA) bus + minibus + microbus/paratransit + Metro (EG) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://hub.tumidata.org/dataset/gtfs_feed_for_the_formal_and_pratransit_in_the_gcr_the_cairo_metro_cairo"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
