#!/usr/bin/env sh
# fetch Pee Dee Regional Transportation Authority (US) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://res2.yourwebsite.life/res/605995d1530fd500214c97ba/65d93f37ca8ed2000ecad7f6"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
