#!/usr/bin/env sh
# fetch Shimanto~Kotsu~Gtfs~Shimantotraffic~Feederbus (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/shimanto-kotsu/feeds/GTFS-Shimantotraffic_Feederbus/files/feed.zip?uid=608977f1-4464-470c-b5f0-aca4dea4757d"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
