#!/usr/bin/env sh
# fetch 石巻市~住民バス~市民バス (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://miyagi.dataeye.jp/resource_download/340"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
