#!/usr/bin/env sh
# fetch 鶴岡市~羽黒地域市営バス朝日地域市営バス (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://www.pref.yamagata.jp/documents/20978/tsuruoka_gtfs_1.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
