#!/usr/bin/env sh
# fetch COMMUNAUTE DE COMMUNES DES PORTES EURELIENNES D'ILE DE FRANCE (FR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://static.data.gouv.fr/resources/ligne-reguliere-du-parc-dactivites-du-val-drouette-pem/20260917-114326/ligne-regu-pem-ccpeif-100926.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
