#!/usr/bin/env sh
# fetch Regione Calabria TPL (OTP GTFS) (IT) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://dati.regione.calabria.it/opendata/dataset/07d67f06-f0ee-4749-9668-1974fc83fab6/resource/7f943a1c-270f-48bc-86f2-02bb9821e900/download/otp_gtfs.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
