#!/usr/bin/env sh
# fetch Israel Ministry of Transport SIRI, republished by Hasadna Open Bus (Public Knowledge Workshop) (IL) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://open-bus-stride-api.hasadna.org.il/siri_vehicle_locations/list?limit=100&order_by=id%20desc"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
