#!/usr/bin/env sh
# fetch Towadakankodentetsu~Toutetsu~Airport~Line (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/towadakankodentetsu/feeds/toutetsu_airport_line/files/feed.zip?uid=8180f39f-c2ed-449c-94ac-a9e76c30e1a3"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
