#!/usr/bin/env sh
# fetch OASTH (Thessaloniki Urban Transport Organization) (GR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://data.gov.gr/dataset/87f127e9-9d06-42b8-8793-029761e28bce/resource/4d2d57e3-de31-4d44-b8b9-98ae605c6bcd/download/oasth.gtfs.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
