#!/usr/bin/env sh
# fetch JR-East / Tokyo Metro rail via ODPT (train location/status) (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.odpt.org/api/v4/odpt:Train?odpt:operator=odpt.Operator:JR-East"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
