#!/usr/bin/env sh
# fetch STSJC / Consórcio 123 (municipal bus network — Viação Saens Peña, Joseense Transporte, Expresso Maringá do Vale) (BR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://raw.githubusercontent.com/jqueguiner/gtfs/main/synthesized/BR/sao-jose-dos-campos/stsjc-consorcio-123-municipal-bus-network-viacao/gtfs/"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
