#!/usr/bin/env sh
# fetch CA ANNONAY RHONE AGGLO (FR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://static.data.gouv.fr/resources/gtfs-reseau-scolaire-coqueligo-annonay-rhone-agglo/20260831-123340/coqueligo-coqueligo-scolaire-2026-2027-v1-test-gtfs-2026-08-31-14-32-27.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
