#!/usr/bin/env sh
# fetch Kimitsucity~Ic~Sp~Local~Buses~Via~Kimitsu~City (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/kimitsucity/feeds/IC-SP_Local_buses_via_Kimitsu_City/files/feed.zip?uid=8f728c13-7b60-4867-a5eb-1f109468cfbb"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
