#!/usr/bin/env sh
# fetch Societe~De~Transport~De~Salaberry~De~Valleyfield (CA) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://www.donneesquebec.ca/recherche/dataset/2c84537c-0a2f-4e6f-aae8-1664bd92d90b/resource/0e4c9cb4-7ab3-40d2-a3d8-a0ecf5d3165c/download/gtfs.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
