#!/usr/bin/env sh
# fetch Fukuoka~Kawasakitown~Kawasakitownfureaibus (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/fukuoka-kawasakitown/feeds/KawasakiTownFureaiBus/files/feed.zip?uid=d6984b0a-4f3c-4723-a3cb-a889845a7bda"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
