#!/usr/bin/env sh
# fetch Métropole d'Aix-Marseille-Provence (FR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://app.mecatran.com/utw/ws/gtfsfeed/static/mamp-cig?apiKey=0262073f524e2f1e1a2f4f254c6b01790b2b2b39"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
