#!/usr/bin/env sh
# fetch Чортківська міська рада (UA) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://data.gov.ua/dataset/e84883c8-4414-4da8-bcb6-bfb7f4e87902/resource/e827527c-a680-40de-9a12-5b088b34b3a6/download/vehicleposition.json"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
