#!/usr/bin/env sh
# fetch Metro do Porto (PT) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://opendata.porto.digital/dataset/15f22603-a216-492a-ab1c-40b1d8aa2f08/resource/33c45455-2a97-481b-8295-bd410d2c31cb/download/horarios_gtfs_mdp_17_07_2026.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
