#!/usr/bin/env sh
# fetch Kyivpastrans (КП Київпастранс) (UA) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://jbb.ghsq.de/gtfs/ua-kyiv.gtfs.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
