#!/usr/bin/env sh
# fetch 富士急バス富士五湖と甲府市周辺~山梨県東部エリア (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://gtfs.buskita.com/gtfs/fjb/gtfs.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
