#!/usr/bin/env sh
# fetch Kitashitara~Odekakehokusetsu (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/kitashitara/feeds/odekakehokusetsu/files/feed.zip?uid=a5c8aa6a-8b32-4f0f-ae54-b47c1c3c7850"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
