#!/usr/bin/env sh
# fetch DER-MG / SEINFRA metropolitan bus (RMBH) + Metrô BH Linha 1 — concessionaires Saritur, Turi, Via Ouro, Expresso Unir, Viação Cisne, Viação Brasília (BR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://raw.githubusercontent.com/jqueguiner/gtfs/main/synthesized/BR/belo-horizonte/der-mg-seinfra-metropolitan-bus-rmbh-metro-bh-li/gtfs/"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
