#!/usr/bin/env sh
# fetch BVG (Berliner Verkehrsbetriebe) — via transport.rest HAFAS wrapper (DE) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://v6.bvg.transport.rest/radar?north=52.55&west=13.30&south=52.45&east=13.50&results=256"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
