#!/usr/bin/env sh
# fetch Kochi~Tobu~Kotsu~Gtfs~Tobutraffic~Localbus (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/kochi-tobu-kotsu/feeds/GTFS-Tobutraffic_Localbus/files/feed.zip?uid=ea397298-327b-49ab-9523-565f21e72eb8"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
