#!/usr/bin/env sh
# fetch TAGO / KOTSA (Ministry of Land) — nationwide real-time city-bus location (incl. Busan cityCode 21) (KR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="http://apis.data.go.kr/1613000/BusLcInfoInqireService/getRouteAcctoBusLcList?cityCode={code}&routeId={id}&serviceKey={KEY}"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
