#!/usr/bin/env sh
# fetch Ashtabula~County~Transportation~Oh~Us (US) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://www.acdjfs.org/_files/archives/0efb20_1e4a561665494d9f963657c8b883e85f.zip?dn=Ashtabula_GTFS_files.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
