#!/usr/bin/env sh
# fetch Iosco~Transit~Corporation~Mi~Us~Flex (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://miruralmobility.org/wp-content/uploads/2025/05/OneDrive_1_5-13-2025.zip#Iosco_Transit_Corporation.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
