#!/usr/bin/env sh
# fetch bustimes.org (open-data aggregator, mirrors BODS SIRI-VM) (GB) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://bustimes.org/vehicles.json?ymax=53.81&xmax=-1.53&ymin=53.78&xmin=-1.57"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
