#!/usr/bin/env sh
# fetch La Regional Vallisoletana S.A (ES) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://drive.usercontent.google.com/u/0/uc?id=1Kzk10f1895vmUF3u2V1YWIpKY0czTTNk&export=download"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
