#!/usr/bin/env sh
# fetch AMTAB Bari (IT) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://opendata.comune.bari.it/dataset/1692384a-748f-47f6-b372-42cca9eaeba0/resource/b40d89da-7499-4703-ab30-80f4344fb2e7/download/google_transit.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
