#!/usr/bin/env sh
# fetch bustimes.org (aggregator of BODS SIRI-VM + TfL + operator AVL) (GB) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://bustimes.org/vehicles.json?ymax=51.55&xmax=-0.05&ymin=51.45&xmin=-0.15"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
