#!/usr/bin/env sh
# fetch Department of Municipalities and Transport (AE) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://pubftp.dmt.gov.ae/main.html?download&weblink=18511ae7285412ca93169260c239d119&realfilename=itc-abudhabi-ae_itc-abudhabi-ae_1651205153_itc-abudhabi-ae.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
