#!/usr/bin/env sh
# fetch KMB / Long Win Bus (data.gov.hk) (HK) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://data.etabus.gov.hk/v1/transport/kmb/route-eta/1/1"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
