#!/usr/bin/env sh
# fetch Tagawacity~Tagawacitycommunitybus (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/tagawacity/feeds/TagawaCityCommunityBus/files/feed.zip?uid=fb47caf5-7c65-42c0-bba8-1b2d85c615b8"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
