#!/usr/bin/env sh
# fetch Tuvr~Urbanosdevilareal (PT) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="http://www.urbanosvilareal.pt/fotos/gca/2019-01-10_gtfs_tuvr_v4_11987813585c3dbf6a271b6.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
