#!/usr/bin/env sh
# fetch Rokkashovillage~Rokkasho~Sharedtaxi (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/rokkashovillage/feeds/rokkasho-sharedtaxi/files/feed.zip?uid=2889c461-d7a5-4639-a0f2-0fd1243c327f"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
