#!/usr/bin/env sh
# fetch Autolinee Toscane - Urbano Pisa (IT) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/e12be15e-5cd2-48d7-84c7-dcfa2976103c/download/44-urbanopisa.gtfs"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
