#!/usr/bin/env sh
# fetch Gran Asuncion metropolitan colectivo operators and line associations (San Isidro, Vanguardia, Magno, Ximex, Lince, Automotores Guarani, Grupo Bene, La Sanlorenzana, Nanduti, Ciudad de Luque, Turismo Aldana, Gonzalez Quinonez, etc.) (PY) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://raw.githubusercontent.com/jqueguiner/gtfs/main/synthesized/PY/asuncion/gran-asuncion-metropolitan-colectivo-operators-a/gtfs/"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
