#!/usr/bin/env sh
# fetch léo fr rt (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="http://auxerre.api.instant-system.com/public/disruptions/gtfs-rt/alert.pb?apikey=8bd10ac5e522fe43eed239439e556b3b"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
