#!/usr/bin/env sh
# fetch Jr~Shikoku~Bus~Kochi~Gtfs~Jrbus~Otochi (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/jr-shikoku-bus-kochi/feeds/GTFS-JRbus_Otochi/files/feed.zip?uid=0a8a650f-46c2-4ef1-a65d-4a1a61b46e34"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
