#!/usr/bin/env sh
# fetch LVB (Leipziger Verkehrsbetriebe / MDV) (DE) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://opendata.leipzig.de/dataset/lvb-fahrplandaten/resource/b38955c4-431c-4e8b-a4ef-9964a3a2c95d/download/gtfsmdvlvb.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
