#!/usr/bin/env sh
# fetch It~Atm~Aziendatrasportidimessina (IT) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="http://smartme-data.unime.it/dataset/f9badaf7-3862-4407-a25a-d347d93a32dd/resource/f0393b28-eb72-4c22-bbbe-b52bcea37f3e/download/atmfeedgtfs.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
