#!/usr/bin/env sh
# fetch RENFE VIAJEROS SOCIEDAD MERCANTIL ESTATAL SA (FR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://ssl.renfe.com/gtransit/Fichero_AV_INT/Renfe_AVE_Int.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
