#!/usr/bin/env sh
# fetch Midland Penetanguishene Transit Service (CA) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://midland.usetransit.com/api/1/public/gtfs/2/gtfs.zip?token=64186b9ee7bea60d7638268206162c0c9c1a3f49e"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
