#!/usr/bin/env sh
# fetch Whitemountainapachetribe~Az~Us (US) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://rapid.nationalrtap.org/GTFSFileManagement/UserUploadFiles/13374/WhiteMtn_Apache_gtfs(1).zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
