#!/usr/bin/env sh
# fetch EPTC Porto Alegre (via World Bank Data Catalog) (BR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://datacatalogfiles.worldbank.org/ddh-published/0038243/1/DR0046590/gtfs_porto_alegre_2020.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
