#!/usr/bin/env sh
# fetch Hanoi BRT — Xí nghiệp Xe buýt nhanh BRT Hà Nội (BRT01, Kim Ma–Yen Nghia) (VN) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://raw.githubusercontent.com/jqueguiner/gtfs/main/synthesized/VN/hanoi/hanoi-brt-xi-nghiep-xe-buyt-nhanh-brt-ha-noi-brt/gtfs/"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
