#!/usr/bin/env sh
# fetch Kochi~Koryo~Kotsu~Gtfs~Koryotraffic~Localbus (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/kochi-koryo-kotsu/feeds/GTFS-Koryotraffic_Localbus/files/feed.zip?uid=1bb88f7e-45fd-459e-85a9-e7ce12e35fb3"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
