#!/usr/bin/env sh
# fetch  Câmara Municipal de Águeda  (PT) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://ckan.sig.cm-agueda.pt/dataset/2c8c47d6-4534-4141-b65a-e8d6da39e064/resource/1ef6b3b7-0726-4c5a-978c-bf6b780c7472/download/gtfs20190510.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
