#!/usr/bin/env sh
# fetch Agglobus~Guyane (FR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api-data.cacl-guyane.fr/v1/gtfs-agglobus-agency/%21sourcefiles"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
