#!/usr/bin/env sh
# fetch Tosashimizucity~Gtfs~Tosashimizucity~Bus (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/tosashimizucity/feeds/GTFS-Tosashimizucity_Bus/files/feed.zip?uid=f9f3f7d3-5c7b-4cb2-8919-dc56ec6209da"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
