#!/usr/bin/env sh
# fetch Communauté d'Agglomération Saint-Lô Agglo (FR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://static.data.gouv.fr/resources/slam-scolaire-lignes-de-transports-scolaires-gtfs-saint-lo-agglo-rentree-2026-2027/20260828-070912/2026-08-27-gtfs-slam-scolaire.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
