#!/usr/bin/env sh
# fetch Coach USA Erie, Orange Westchester Link, ShortLine Hudson, Suburban Transit, Community Coach, Rockland Coaches, Newark Airport Express, Wisconsin Coach Lines, Van Galder (Coach USA), Coach Suburban Transit Corporation, Coach Community Coach, Coach Hudson Transit Lines, Coach Newark Express, Waukesha County Transit (CA) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.prod.coachusa.com/gtfs"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
