#!/usr/bin/env sh
# fetch Kimitsucity~Ic~Local~Buses~Via~Kimitsu~City~And~Kimitsu~City~Community~Bus (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/kimitsucity/feeds/IC_Local_buses_via_Kimitsu_City_and_Kimitsu_City_Community_Bus/files/feed.zip?uid=3df38e7e-cb7b-42e3-a73b-1f4dba8733d2"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
