#!/usr/bin/env sh
# fetch Samukawatown~Mokusei~Go~Kuramiomuraroute (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/samukawatown/feeds/mokusei-go_kuramiomuraroute/files/feed.zip?uid=fab9113f-6ae2-4e70-b3e7-931ead4394a6"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
