#!/usr/bin/env sh
# fetch Pau~Béarn~Pyrénées~Scolaris (FR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://data.idelis.fr/api/explore/v2.1/catalog/datasets/fichier-des-donnees-theoriques-du-reseau-scolaris-au-format-gtfs/files/5aa87161316bb5f3fc8233ed07227f54"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
