#!/usr/bin/env sh
# fetch Kosugevillage~Kosugesoneibus (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/kosugevillage/feeds/kosugesoneibus/files/feed.zip?uid=6e401d25-81a6-4ea4-adac-d311997992a2"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
