#!/usr/bin/env sh
# fetch TDX — Metro live board (TRTC Taipei, KRTC Kaohsiung, TYMC, KLRT) (TW) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://tdx.transportdata.tw/api/basic/v2/Rail/Metro/LiveBoard/{System}"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
