#!/usr/bin/env sh
# fetch bustimes.org (Translink Metro/Glider AVL) (GB) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://bustimes.org/vehicles.json?ymax=54.62&xmax=-5.88&ymin=54.57&xmin=-5.96"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
