#!/usr/bin/env sh
# fetch NEMUS (Réseau de transports de Flers Agglo) (FR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://static.data.gouv.fr/resources/reseau-nemus/20260722-100829/gtfs-au-100726.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
