#!/usr/bin/env sh
# fetch Transp'Or - Pays de l'Or Agglomération (FR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://static.data.gouv.fr/resources/offre-transport-en-commun-du-reseau-transpor-gtfs/20260630-083249/transp-or-ete-saison-2026-sans-tad-gtfs-2026-06-30-10-32-30.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
