#!/usr/bin/env sh
# fetch Région des Pays de la Loire (FR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://www.data.gouv.fr/api/1/datasets/r/916752e4-5daa-48bd-8bc1-4dd8d64f1d4a"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
