#!/usr/bin/env sh
# fetch STCP — Sociedade de Transportes Colectivos do Porto (PT) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://opendata.porto.digital/dataset/5275c986-592c-43f5-8f87-aabbd4e4f3a4/resource/2bfd5b9e-5f09-49df-af33-3df622b2f3c9/download/gtfs_feed.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
