#!/usr/bin/env sh
# fetch VRR (Verkehrsverbund Rhein-Ruhr) / MENTZ EFA (DE) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://efa.vrr.de/standard/XML_DM_REQUEST?outputFormat=JSON&language=de&stateless=1&coordOutputFormat=WGS84%5Bdd.ddddd%5D&type_dm=stop&name_dm=20009289&mode=direct&useRealtime=1&itdDateTimeDepArr=dep"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
