#!/usr/bin/env python3
"""Build the country/city/agency tree + catalog.csv + README table from a
Mobility-Database dump (scripts/ingest_mdb.py writes data/feeds_full.json)."""
import json, os, re, csv, sys, unicodedata, hashlib
from collections import defaultdict, Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "feeds_full.json")

CC_NAME = {  # minimal ISO-2 -> name (extend freely)
 'FR':'France','US':'United States','CA':'Canada','JP':'Japan','ES':'Spain','IT':'Italy','GB':'United Kingdom',
 'DE':'Germany','SE':'Sweden','PL':'Poland','AU':'Australia','BR':'Brazil','IN':'India','NL':'Netherlands',
 'BE':'Belgium','CH':'Switzerland','AT':'Austria','PT':'Portugal','IE':'Ireland','FI':'Finland','NO':'Norway',
 'DK':'Denmark','CZ':'Czechia','MX':'Mexico','AR':'Argentina','CL':'Chile','NZ':'New Zealand','ID':'Indonesia',
 'ZA':'South Africa','NG':'Nigeria','GH':'Ghana','EE':'Estonia','LT':'Lithuania','LV':'Latvia','GR':'Greece',
 'HU':'Hungary','RO':'Romania','SK':'Slovakia','SI':'Slovenia','HR':'Croatia','RS':'Serbia','BG':'Bulgaria',
 'LU':'Luxembourg','IS':'Iceland','MT':'Malta','CY':'Cyprus','TR':'Turkey','IL':'Israel','TW':'Taiwan',
 'HK':'Hong Kong','SG':'Singapore','KR':'South Korea','TH':'Thailand','MY':'Malaysia','PH':'Philippines',
}


def slug(s, fallback="unknown"):
    s = (s or "").strip()
    if not s:
        return fallback
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    s = re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-").lower()
    return s or fallback


def main():
    feeds = json.load(open(SRC))
    feeds = [f for f in feeds if f["status"] not in ("deprecated", "inactive")
             and (f.get("producer_url") or f.get("hosted_url"))]

    # wipe old country dirs
    for d in os.listdir(ROOT):
        if len(d) == 2 and d.isupper() and os.path.isdir(os.path.join(ROOT, d)):
            import shutil; shutil.rmtree(os.path.join(ROOT, d))

    rows = []
    per_country = defaultdict(lambda: {"feeds": 0, "cities": set(), "agencies": set()})
    for f in feeds:
        cc = (f["cc"] or "XX").upper()
        if not re.fullmatch(r"[A-Z]{2}", cc):
            cc = "XX"
        city = f["city"] or f["subdiv"] or "national"
        agency = f["provider"] or f["name"] or f["id"]
        cslug = (slug(city, "")[:40] or "unknown")
        # ascii base + short hash of the source id => always ascii, bounded, unique
        uid = hashlib.md5(str(f["id"]).encode("utf-8")).hexdigest()[:8]
        aslug = (slug(agency, "")[:48] or "op") + "-" + uid
        d = os.path.join(ROOT, cc, cslug, aslug)
        os.makedirs(d, exist_ok=True)
        manifest = {
            "agency": {"name": agency, "country": cc, "subdivision": f["subdiv"], "city": f["city"] or None},
            "feed": {"format": "gtfs", "url": f["producer_url"] or f["hosted_url"],
                     "mdb_id": f["id"], "license": f["license"] or None},
            "bbox": f["bbox"] or None,
            "source": "mobility-database",
            "status": "active",
        }
        json.dump(manifest, open(os.path.join(d, "feed.json"), "w"), indent=2, ensure_ascii=False)
        url = f["producer_url"] or f["hosted_url"]
        fetch = (
            "#!/usr/bin/env sh\n"
            f"# fetch {agency} ({cc}) GTFS -> gtfs.zip. Regenerated by build_repo.py.\n"
            f'URL="{url}"\n'
            'DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"\n'
            'echo "GET $URL"\n'
            'curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }\n'
            'unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }\n'
            'echo "ok: $DIR/gtfs.zip"\n'
        )
        fp = os.path.join(d, "fetch.sh")
        open(fp, "w").write(fetch)
        os.chmod(fp, 0o755)
        rows.append([cc, city, agency, f["producer_url"] or f["hosted_url"], f["id"], f["license"], "active"])
        pc = per_country[cc]
        pc["feeds"] += 1; pc["cities"].add(cslug); pc["agencies"].add(aslug)

    # root helper: fetch every (or one country's) operator feed
    fa = os.path.join(ROOT, "fetch_all.sh")
    open(fa, "w").write(
        "#!/usr/bin/env sh\n"
        "# Download every operator's GTFS by running each fetch.sh.\n"
        "# Usage: ./fetch_all.sh [COUNTRY]   e.g. ./fetch_all.sh FR\n"
        'ROOT="$(CDPATH= cd "$(dirname "$0")" && pwd)"; CC="${1:-}"\n'
        'find "$ROOT/$CC" -name fetch.sh 2>/dev/null | while read s; do sh "$s" || true; done\n'
    )
    os.chmod(fa, 0o755)

    # flat catalog
    os.makedirs(os.path.join(ROOT, "data"), exist_ok=True)
    with open(os.path.join(ROOT, "catalog.csv"), "w", newline="") as fh:
        w = csv.writer(fh); w.writerow(["country", "city", "agency", "feed_url", "mdb_id", "license", "status"])
        w.writerows(sorted(rows))

    # README with coverage table
    order = sorted(per_country, key=lambda c: (c not in ("FR", "US"), -per_country[c]["feeds"]))
    tot_f = sum(v["feeds"] for v in per_country.values())
    tot_ci = sum(len(v["cities"]) for v in per_country.values())
    lines = []
    lines.append("# gtfs — open public-transport catalog\n")
    lines.append("Every public-transport operator we can find, organised **country → city → operator**, "
                 "each with a `feed.json` (GTFS URL + license + bbox). Scraped from open catalogs + agency/gov "
                 "sites, LLM-normalized when the source isn't already GTFS. Priority: 🇫🇷 France, 🇺🇸 USA.\n")
    lines.append(f"**{tot_f} feeds · {tot_ci} cities · {len(per_country)} countries** · updated automatically.\n")
    lines.append("## Layout\n```\n<COUNTRY>/<city>/<operator>/feed.json\n```\n")
    lines.append("`feed.json` = agency + GTFS url + license + bbox (the exchange format). Each operator folder "
                 "also ships a `fetch.sh` that downloads *that* operator's GTFS to `gtfs.zip` (validates "
                 "`stops.txt`). `./fetch_all.sh [COUNTRY]` runs them all. Flat index: `catalog.csv`.\n")
    lines.append("## Coverage\n")
    lines.append("| Country | Feeds | Cities | Operators |")
    lines.append("|---|--:|--:|--:|")
    for cc in order:
        v = per_country[cc]
        name = CC_NAME.get(cc, cc)
        flag = "".join(chr(0x1F1E6 + ord(x) - 65) for x in cc) if len(cc) == 2 and cc.isalpha() else ""
        lines.append(f"| {flag} {name} | {v['feeds']} | {len(v['cities'])} | {len(v['agencies'])} |")
    lines.append("\n## How it works\n")
    lines.append("Feeds are merged from multiple open registries + national access points, then placed to "
                 "country/city by geohash or a stop coordinate:\n")
    lines.append("- `scripts/ingest_mdb.py` — Mobility Database catalog\n"
                 "- `scripts/scrape_transitland.py` — Transitland Atlas (Interline), ~4000 feeds, superset of MDB\n"
                 "- `scripts/scrape_france.py` — transport.data.gouv.fr (FR national aggregator)\n"
                 "- `scripts/scrape_<cc>.py` — per-country National Access Points (EU-mandated NAPs etc.)\n"
                 "- `scripts/resolve_unplaced.py` — download GTFS, read a stop lat/lon, reverse-geocode any feed "
                 "still missing a country\n"
                 "- `scripts/llm_normalize.py` — non-GTFS sources (PDF/HTML/CSV) → GTFS via an LLM\n"
                 "- `scripts/build_repo.py` — regenerates this tree, `catalog.csv`, and the table above\n")
    lines.append("\n`XX` = feeds whose country couldn't be determined yet (unreachable feed / no stops). "
                 "CI reruns weekly (`.github/workflows/refresh.yml`). See `CONTRIBUTING.md` to add a network.\n")
    open(os.path.join(ROOT, "README.md"), "w").write("\n".join(lines))
    print(f"built {tot_f} feeds, {tot_ci} cities, {len(per_country)} countries")
    print("FR:", per_country.get("FR"), "US feeds:", per_country["US"]["feeds"])


if __name__ == "__main__":
    main()
