#!/usr/bin/env sh
# fetch Awajicity~Awaji~Jenova~Line~Akashi~Iwaya (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/awajicity/feeds/awaji-jenova-line-akashi-iwaya/files/feed.zip?uid=da2b1c4c-454e-430c-a149-10dc862290be"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
