#!/usr/bin/env sh
# fetch Namegatacity~Bus~Namegata~Ibaraki~Jp (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/namegatacity/feeds/bus-namegata-ibaraki-jp/files/feed.zip?uid=baf9dd30-4f81-42a7-ba97-7f3e762d71df"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
