#!/usr/bin/env sh
# fetch AMB - Area Metropolitana de Barcelona (ES) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="http://www.amb.cat/Mobilitat/OpenData/google_transit.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
