#!/usr/bin/env sh
# fetch SNCF TER — Saint-Florent-sur-Cher (FR) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://eu.ftp.opendatasoft.com/sncf/gtfs/export-ter-gtfs-last.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
