#!/usr/bin/env sh
# fetch 下仁田町~しもにたバス (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://www.town.shimonita.lg.jp/shimonita-bus/m01/gtfs.20230324.shimonita.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
