#!/usr/bin/env sh
# fetch Midland-Odessa Urban Transit District (US) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="http://nebula.wsimg.com/d1765d43782cc9d2d026c4925e8a189b?AccessKeyId=9E919CD400BCF69A0E80&disposition=0&alloworigin=1"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
