#!/usr/bin/env sh
# fetch Clarksville~Tn~Us (US) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://www.clarksvilletn.gov/DocumentCenter/View/7132/CTS-11252025-GTFS-Data"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
