#!/usr/bin/env sh
# fetch Minamishinshu~Minamishinshu~Ooshika~1 (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/minamishinshu/feeds/Minamishinshu-Ooshika-1/files/feed.zip?uid=70518f7b-89d4-41d1-ba8e-47b9eccd0cfb"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
