#!/usr/bin/env sh
# fetch Kuratetown~Kuratetownsmilebusmiyawakaline (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/kuratetown/feeds/KurateTownSmileBusMiyawakaLine/files/feed.zip?uid=5b3be531-8f76-4a79-a2f6-adce3f78e633"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
