#!/usr/bin/env sh
# fetch Município de Coimbra (PT) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://dados.gov.pt/s/resources/gtfs-estaticos-servicos-municipalizados-de-transportes-urbanos-de-coimbra/20260805-132033-7fd48f3d/smtuc-static-gtfs-20260729-210624-307679-409bb121.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
