#!/usr/bin/env sh
# fetch 北海道拓殖バス~一般路線コミュニティバス音更町~新得町~清水町 (XX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://www.takubus.com/app/download/11236187979/GTFS_regular_line20230526.zip?t=1685093868"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
