#!/usr/bin/env sh
# fetch hvv (Hamburger Verkehrsverbund) (DE) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://daten.transparenz.hamburg.de/Dataport.HmbTG.ZS.Webservice.GetRessource100/GetRessource100.svc/7dd559f6-5d5f-455c-b42f-a1b8494b4d1e/Upload__hvv_Rohdaten_GTFS_Fpl_20250806.ZIP"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
