#!/usr/bin/env sh
# fetch Good Earth Transit (US) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://america.usetransit.com/api/1/public/gtfs/7/gtfs.zip?token=987dbc22d5980a4be397675617103334454552804"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
