#!/usr/bin/env sh
# fetch Kochi~Ekimae~Kanko~Gtfs~Ekimae~Airportbus (JP) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.gtfs-data.jp/v2/organizations/kochi-ekimae-kanko/feeds/GTFS-Ekimae_Airportbus/files/feed.zip?uid=b5df8042-8d88-4a9f-83d3-e258bf0ff26a"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
