#!/usr/bin/env sh
# fetch Mitransporte~Jalisco~Mx (MX) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://datos.jalisco.gob.mx/sites/default/files/rutas_mi_transporte_amg_jalisco_07.12.2021.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
