#!/usr/bin/env sh
# fetch NVV (Nordhessischer VerkehrsVerbund) (DE) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://api.opendata-oepnv.de/dataset/4c35703c-62d2-463a-8f8d-014594ab6e30/resource/14c51276-9f32-448b-a3bd-57404cb491c0/download/gtfs-b.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
