#!/usr/bin/env sh
# fetch VVS (Verkehrs- und Tarifverbund Stuttgart) / MENTZ EFA (DE) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://www3.vvs.de/vvs/XSLT_DM_REQUEST?outputFormat=JSON&language=de&stateless=1&type_dm=stop&name_dm=5006115&useRealtime=1&mode=direct&itdDateTimeDepArr=dep"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
