#!/usr/bin/env sh
# fetch bustimes.org (First Leeds / West Yorkshire AVL via BODS) (GB) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://bustimes.org/vehicles.json?ymax=53.82&xmax=-1.50&ymin=53.77&xmin=-1.60"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
