#!/usr/bin/env sh
# fetch Miccolis S.p.A. (IT) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="http://dati.comune.matera.it/dataset/d0c92871-38dd-440b-95d1-7155b522d57e/resource/cb97b36d-293e-4dfb-84e3-50ba7e3d9d50/download/gtfs_matera.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
