#!/usr/bin/env sh
# fetch TIB / CTM (Consorci de Transports de Mallorca) (ES) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://www.tib.org/documents/20124/478141/ctm-mallorca-es.zip/8481f8a8-7907-5118-4934-5b428b458ae7?t=1786105923724"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
