#!/usr/bin/env sh
# fetch Autolinee Toscane - Emg Urbano Volterra (IT) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/38ba32a8-01b9-4ffd-baed-2551ad765180/download/262-emgurbanovolterra.gtfs"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
