#!/usr/bin/env sh
# fetch Prince~Albert~Sk~Ca (CA) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://media-002-ca.cdn.govstack.com/citypa-015-ca/media/gnsfaref/2025-01-20-google-transit-gtfs.zip"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
