#!/usr/bin/env sh
# fetch bustimes.org (Lothian AVL via BODS) (GB) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://bustimes.org/vehicles.json?ymax=55.99&xmax=-3.10&ymin=55.92&xmin=-3.25"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
