#!/usr/bin/env sh
# fetch VMS (Verkehrsverbund Mittelsachsen) — CVAG / City-Bahn Chemnitz (DE) GTFS -> gtfs.zip. Regenerated by build_repo.py.
URL="https://efa.vvo-online.de/VMSSL3/XSLT_DM_REQUEST?outputFormat=rapidJSON&type_dm=any&name_dm=Chemnitz+Zentralhaltestelle&useRealtime=1&mode=direct&limit=10"
DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
echo "GET $URL"
curl -fSL --retry 3 --max-time 300 -o "$DIR/gtfs.zip" "$URL" || { echo "download failed"; exit 1; }
unzip -l "$DIR/gtfs.zip" 2>/dev/null | grep -q stops.txt || { echo "not valid GTFS (no stops.txt)"; exit 2; }
echo "ok: $DIR/gtfs.zip"
